# Generated by Django 5.1 on 2024-08-15 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('usp_number', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('speaker', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('date_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('begin', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talk')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('online', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talk')),
            ],
            options={
                'unique_together': {('student', 'talk')},
            },
        ),
    ]
