# Generated by Django 5.1.8 on 2025-05-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='online',
        ),
    ]
