name: ruff linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      # You may pin to the exact commit or the version.
      # uses: astral-sh/ruff-action@c6bea5606c33b5d04902374392d9233464b90660
      uses: astral-sh/ruff-action@v3.3.0
      with:
        src: ./src
      
              
